# Generated by Django 4.2.1 on 2023-05-13 15:02

import json

from api.models import Exercise, Muscle, MusclePerExercise
from django.db import migrations


def load_data(apps, scheme_editor):
    with open("./api/exercises.json") as file:
        exercises = json.load(file)
        for exercise in exercises:
            primary_muscle_names = exercise["primaryMuscles"]
            secondary_muscle_names = exercise["secondaryMuscles"]
            exercise_name = exercise["name"]
            exercise_object, _ = Exercise.objects.get_or_create(name=exercise_name)
            process_primary_muscle(
                exercise=exercise_object, primary_muscles=primary_muscle_names
            )

            process_secondary_muscle(
                exercise=exercise_object, secondary_muscles=secondary_muscle_names
            )


def process_primary_muscle(exercise: Exercise, primary_muscles: list[str]):
    for muscle_name in primary_muscles:
        muscle, _ = Muscle.objects.get_or_create(name=muscle_name)
        MusclePerExercise.objects.get_or_create(
            muscle=muscle, exercise=exercise, is_primary_muscle=1
        )


def process_secondary_muscle(exercise: Exercise, secondary_muscles: list[str]):
    for muscle_name in secondary_muscles:
        muscle, _ = Muscle.objects.get_or_create(name=muscle_name)
        MusclePerExercise.objects.get_or_create(
            muscle=muscle, exercise=exercise, is_primary_muscle=0
        )


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_auto_20230513_1442"),
    ]

    operations = [migrations.RunPython(load_data)]
