# Generated by Django 4.2.2 on 2023-09-04 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_auto_20230610_2048"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkoutSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_datetime", models.DateTimeField()),
                ("end_datetime", models.DateTimeField()),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("gym", "Gym"),
                            ("home", "Home"),
                            ("outdoor", "Outdoor"),
                        ],
                        default="home",
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workout_sessions",
                        to="api.user",
                    ),
                ),
                (
                    "workout",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workout_sessions",
                        to="api.workout",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExerciseLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sets_made", models.IntegerField()),
                ("reps_per_set_made", models.JSONField(default=[])),
                ("weight_used", models.JSONField(default=[])),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises_logs",
                        to="api.exercise",
                    ),
                ),
                (
                    "workout_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises_logs",
                        to="api.workoutsession",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="workoutsession",
            constraint=models.CheckConstraint(
                check=models.Q(("end_datetime__gt", models.F("start_datetime"))),
                name="check_start_datime",
            ),
        ),
        migrations.AddConstraint(
            model_name="workoutsession",
            constraint=models.UniqueConstraint(
                fields=("start_datetime",), name="unique_start_datetime"
            ),
        ),
    ]
