# Generated by Django 4.2.1 on 2023-05-29 14:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_workoutexercise_reps_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="created",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
