# Generated by Django 4.2.1 on 2023-05-29 14:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_workout_created"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workout",
            name="name",
        ),
    ]
