# Generated by Django 4.2.1 on 2023-05-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_remove_workout_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workout",
            name="created",
            field=models.DateField(auto_now_add=True),
        ),
    ]
