name: Test
on:
  workflow_call: 
  # Allows you to call this workflow within another workflow
  workflow_dispatch: 
  # Allows you to run this workflow manually from the Actions tab
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15.3
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testing
          POSTGRES_HOST: localhost
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install --dev --system
      - name: Set environment variables
        run: |
          echo "DB_NAME=testing" >> $GITHUB_ENV
          echo "DB_USER=postgres" >> $GITHUB_ENV
          echo "DB_PASSWORD=postgres" >> $GITHUB_ENV
          echo "DB_HOST=localhost" >> $GITHUB_ENV
          echo "DB_PORT=5432" >> $GITHUB_ENV
      - name: Flake8 checks
        run: pipenv run flake8
      - name: Run unit tests and collect coverage
        run: python -m pytest -vv --tb=native --create-db --nomigrations --cov-report term-missing --cov=./workout 
      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v3
